### ISSUE TITLE
Author bio: Alex

### ISSUE THREAD

**Issue by swglad** [sourcemash/Kemeny#2]
Name, Address, Email, and a Brief Bio.

Post it directly below; this is for the online application.

**Comment by alexgerstein** [comment]
Alex Gerstein
68 Whippoorwill Lake Road, Chappaqua, NY 10514
alexander.s.gerstein.15@dartmouth.edu

Alex Gerstein '15 majored in Computer Science at Dartmouth. He enjoys building tools that simplify the lives of others, including sites for Dartmouth students to organize their class schedule (dartplan.com) and to find roommates in new cities during off-terms (lodjers.com).
