### ISSUE TITLE
Choose a Judging Category

### ISSUE THREAD

**Issue by swglad** [sourcemash/Kemeny#9]
To encourage diversity in undergraduate computing, the Kemeny prize will be awarded in two separate categories: Innovation and System Design. 

While projects in both categories are expected to be innovative and useful, the Innovation category places special emphasis on novel uses of computing, while the System Design category places additional emphasis on traditional Computer Science and Software Engineering metrics, such as algorithms and data structures used in the implementation of the project. (Your entry may suggest a category, but the judges may very well end up deciding it better fits in the other one.) - See more at: http://web.cs.dartmouth.edu/undergraduate/john-g-kemeny-computing-prize#sthash.A7ifCCE3.dpuf

**Comment by swglad** [comment]
Innovation --> Sourcemash. System Design --> Sourcemash/Categorizer.

@alexgerstein what do you think?

**Comment by swglad** [comment]
My only concern is that, looking at previous winners, calling it "System Design" may be a bit aggressive.

**Comment by alexgerstein** [comment]
Let's go with innovation. They say they'll adjust categories if they think it's better in the other one anyway.
